# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "crosschain_models"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "crosschain"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"
  - "dbt_packages"

on-run-start:
  - "{{ create_sps() }}"
  - '{{ create_udfs() }}'
  - '{{ sp_create_bulk_fill_cmc_historical_price_gaps() }}'
  - '{{ sp_create_bulk_get_coin_gecko_asset_metadata() }}'
  - '{{ sp_create_bulk_get_coin_market_cap_asset_metadata() }}'
  - '{{ sp_create_bulk_get_coin_market_cap_prices() }}'
  - '{{ sp_create_bulk_get_coin_gecko_prices() }}'
  - '{{ sp_create_bulk_get_coin_market_cap_hourly_ohlc() }}'
  - '{{ sp_refresh_external_table_by_recent_date() }}'
  - '{{create_tasks()}}'


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  +copy_grants: true
  +persist_docs:
    relation: true
    columns: true

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

vars:
  "dbt_date:time_zone": GMT
