name: dbt_run_scheduled_daily
run-name: dbt_run_scheduled_daily

on:
  workflow_dispatch:
  schedule:
    # Runs 02:00 daily (see https://crontab.guru)
    - cron: '0 2 * * *'
    
env:
  DBT_PROFILES_DIR: "${{ secrets.DBT_PROFILES_DIR }}"

  ACCOUNT: "${{ secrets.ACCOUNT }}"
  ROLE: "${{ secrets.ROLE }}"
  USER: "${{ secrets.USER }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  REGION: "${{ secrets.REGION }}"
  DATABASE: "${{ secrets.DATABASE }}"
  WAREHOUSE: "${{ secrets.WAREHOUSE }}"
  SCHEMA: "${{ secrets.SCHEMA }}"


jobs:
  called_workflow_template:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/dbt_run_template.yml@main
    with:
      dbt_command: dbt run -s ./models --exclude models/silver/hourly_prices+ models/bronze/bronze_api models/silver/utilities models/silver/observability/silver__data_delay.sql
      environment: workflow_prod
      warehouse: ${{ vars.WAREHOUSE }}
    secrets: inherit 
