name: dbt_run_adhoc
run-name: dbt_run_adhoc

on:
  workflow_dispatch:
    branches:
      - "main"
    inputs:
      environment:
        type: choice 
        description: DBT Run Environment
        required: true
        options:
          - dev
          - prod
        default: dev
      warehouse:
        type: choice 
        description: Snowflake warehouse
        required: true 
        options:
          - DBT
          - DBT_CLOUD
          - DBT_EMERGENCY
      dbt_command:
        type: string
        description: 'DBT Run Command'
        required: true
      update_udfs:
          type: string 
          description: Bloolean to control updating UDFs and Stored Procedures
          required: true
          default: 'False'
        
    
env:
  DBT_PROFILES_DIR: "${{ vars.DBT_PROFILES_DIR }}"
  DBT_VERSION: "${{ vars.DBT_VERSION }}"
  ACCOUNT: "${{ vars.ACCOUNT }}"
  ROLE: "${{ vars.ROLE }}"
  USER: "${{ vars.USER }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  REGION: "${{ vars.REGION }}"
  DATABASE: "${{ vars.DATABASE }}"
  WAREHOUSE: "${{ inputs.WAREHOUSE }}"
  SCHEMA: "${{ vars.SCHEMA }}"
  UPDATE_UDFS_AND_SPS: ${{ inputs.update_udfs }}
  STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES: True


jobs:
  called_workflow_template:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/dbt_run_template.yml@STREAM-346-CACHE-PIP
    with:
      dbt_command: ${{ inputs.dbt_command }}
      environment: workflow_${{ inputs.environment }}
      warehouse: ${{ inputs.warehouse }}
    secrets: inherit 
  