name: dbt_run_data_snapshot
run-name: dbt_run_data_snapshot

on:
  workflow_dispatch:
  schedule:
    # Runs every 10 mins (see https://crontab.guru)
    - cron: '*/10 * * * *'
    
env:
  DBT_PROFILES_DIR: "${{ secrets.DBT_PROFILES_DIR }}"

  ACCOUNT: "${{ secrets.ACCOUNT }}"
  ROLE: "${{ secrets.ROLE }}"
  USER: "${{ secrets.USER }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  REGION: "${{ secrets.REGION }}"
  DATABASE: "${{ secrets.DATABASE }}"
  WAREHOUSE: "${{ secrets.WAREHOUSE }}"
  SCHEMA: "${{ secrets.SCHEMA }}"


jobs:
  called_workflow_template:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/dbt_run_template.yml@main
    with:
      dbt_command: dbt run -m models/silver/observability/silver__data_delay.sql
      environment: workflow_prod
      warehouse: ${{ vars.WAREHOUSE }}
    secrets: inherit 
