name: dbt_run_streamline_prices_realtime
run-name: dbt_run_streamline_prices_realtime

on:
  workflow_dispatch:
  schedule:
      # Runs at minute 25 every hour (see https://crontab.guru)
      - cron: '25 * * * *'  
    
env:
  DBT_PROFILES_DIR: "${{ vars.DBT_PROFILES_DIR }}"
  DBT_VERSION: "${{ vars.DBT_VERSION }}"
  ACCOUNT: "${{ vars.ACCOUNT }}"
  ROLE: "${{ vars.ROLE }}"
  USER: "${{ vars.USER }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  REGION: "${{ vars.REGION }}"
  DATABASE: "${{ vars.DATABASE }}"
  WAREHOUSE: "${{ vars.WAREHOUSE }}"
  SCHEMA: "${{ vars.SCHEMA }}"


jobs:
  called_workflow_template:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/dbt_run_template.yml@main
    with:
      dbt_command: dbt run --vars '{"STREAMLINE_INVOKE_STREAMS":True}' -m "crosschain_models,tag:streamline_prices_realtime2"
      environment: workflow_prod
      warehouse: ${{ vars.WAREHOUSE }}
    secrets: inherit 
          
