name: dbt_run_streamline_coin_gecko_market_chart_backfill
run-name: dbt_run_streamline_coin_gecko_market_chart_backfill

on:
  workflow_dispatch:
  schedule:
    - cron: '15 * * * *'
    
env:
  DBT_PROFILES_DIR: "${{ vars.DBT_PROFILES_DIR }}"
  DBT_VERSION: "${{ vars.DBT_VERSION }}"
  ACCOUNT: "${{ vars.ACCOUNT }}"
  ROLE: "${{ vars.ROLE }}"
  USER: "${{ vars.USER }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  REGION: "${{ vars.REGION }}"
  DATABASE: "${{ vars.DATABASE }}"
  WAREHOUSE: "${{ vars.WAREHOUSE }}"
  SCHEMA: "${{ vars.SCHEMA }}"
  STREAMLINE_INVOKE_STREAMS: true
  STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES: false


jobs:
  called_workflow_template:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/dbt_run_template.yml@main
    with:
      dbt_command: dbt run -m 1+models/streamline/backfill/streamline__get_prices_history.sql 
      environment: workflow_prod
      warehouse: ${{ vars.WAREHOUSE }}
    secrets: inherit 
          
