name: Slack Protocol Alert
on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  notify-protocols:
    runs-on: ubuntu-latest
    environment: workflow_prod
    env:
      DBT_PROFILES_DIR: "${{ vars.DBT_PROFILES_DIR }}"
      DBT_VERSION: "${{ vars.DBT_VERSION }}"
      ACCOUNT: "${{ vars.ACCOUNT }}"
      ROLE: "${{ vars.ROLE }}"
      USER: "${{ vars.USER }}"
      PASSWORD: "${{ secrets.PASSWORD }}"
      REGION: "${{ vars.REGION }}"
      DATABASE: "${{ vars.DATABASE }}"
      WAREHOUSE: "${{ vars.WAREHOUSE }}"
      SCHEMA: "${{ vars.SCHEMA }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          dbt deps
          
      - name: Send protocol alert
        run: |
          python scripts/slack_protocol_alert.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}