version: 2

sources:
  - name: crosschain_dev_silver
    database: crosschain_dev
    schema: silver
    tables:
      - name: dates_table
  - name: ethereum_core
    database: ethereum
    schema: core
    tables:
      - name: fact_transactions
      - name: fact_token_transfers
      - name: fact_traces
      - name: ez_current_balances
      - name: dim_contracts
  - name: ethereum_price
    database: ethereum
    schema: price
    tables:
      - name: fact_hourly_token_prices
  - name: ethereum_nft
    database: ethereum
    schema: nft 
    tables:
      - name: ez_nft_sales
      - name: ez_nft_transfers
  - name: ethereum_defi
    database: ethereum
    schema: defi
    tables:
      - name: ez_dex_swaps
  - name: ethereum_silver
    database: ethereum
    schema: silver
    tables:
      - name: logs
      - name: decoded_logs
      - name: traces
      - name: transactions
      - name: labels
      - name: abis
      - name: contracts
      - name: complete_event_abis
  - name: ethereum_ens
    database: ethereum
    schema: ens
    tables:
      - name: ez_ens_domains
  - name: crosschain_silver
    database: crosschain
    schema: silver
    tables:
      - name: godmode_nft_minters
      - name: optimism_delegates
      - name: osmosis_developer_vesting_receivers
      - name: aave_balancer_addresses
      - name: uniswap_verified_token_tags
  - name: crosschain_core
    database: crosschain
    schema: core
    tables:
      - name: address_labels
      - name: dim_labels
  - name: ethereum_silver_nft
    database: ethereum
    schema: silver_nft
    tables:
      - name: cryptopunk_sales
      - name: looksrare_sales
      - name: nftx_sales
      - name: opensea_sales
      - name: rarible_sales
      - name: seaport_sales
      - name: x2y2_sales
      - name: blur_sales
      - name: sudoswap_sales
      - name: complete_nft_sales
  - name: algorand_core
    database: algorand
    schema: core
    tables:
      - name: ez_transfer
      - name: dim_asset
  - name: arbitrum_silver
    database: arbitrum
    schema: silver
    tables:
      - name: logs
      - name: traces
      - name: transactions
      - name: contracts
      - name: complete_event_abis
      - name: decoded_logs
      - name: abis
      - name: complete_nft_sales
  - name: arbitrum_core
    database: arbitrum
    schema: core
    tables:
      - name: fact_token_transfers
      - name: fact_traces
      - name: dim_contracts
  - name: arbitrum_defi
    database: arbitrum
    schema: defi
    tables:
      - name: ez_dex_swaps
  - name: avalanche_silver
    database: avalanche
    schema: silver
    tables:
      - name: logs
      - name: decoded_logs
      - name: traces
      - name: transactions
      - name: abis
      - name: contracts
      - name: complete_event_abis
      - name: complete_nft_sales
  - name: avalanche_core
    database: avalanche
    schema: core
    tables:
      - name: fact_token_transfers
      - name: fact_traces
      - name: dim_contracts
  - name: avalanche_defi
    database: avalanche
    schema: defi
    tables:
      - name: ez_dex_swaps
  - name: polygon_silver
    database: polygon
    schema: silver
    tables:
      - name: logs
      - name: decoded_logs
      - name: traces
      - name: transactions
      - name: abis
      - name: contracts
      - name: complete_event_abis
      - name: complete_nft_sales
  - name: polygon_core
    database: polygon
    schema: core
    tables:
      - name: fact_token_transfers
      - name: fact_traces
      - name: dim_contracts
  - name: polygon_defi
    database: polygon
    schema: defi
    tables:
      - name: ez_dex_swaps
  - name: optimism_silver
    database: optimism
    schema: silver
    tables:
      - name: logs
      - name: traces
      - name: transactions
      - name: contracts
      - name: complete_event_abis
      - name: decoded_logs
      - name: abis
      - name: complete_nft_sales
  - name: optimism_core
    database: optimism
    schema: core
    tables:
      - name: fact_token_transfers
      - name: fact_traces
      - name: dim_contracts
  - name: optimism_defi
    database: optimism
    schema: defi
    tables:
      - name: ez_dex_swaps
  - name: bsc_silver
    database: bsc
    schema: silver
    tables:
      - name: logs
      - name: traces
      - name: transactions
      - name: contracts
      - name: abis
      - name: complete_event_abis
      - name: decoded_logs
      - name: complete_nft_sales
  - name: bsc_core
    database: bsc
    schema: core
    tables:
      - name: fact_token_transfers
      - name: fact_traces
      - name: dim_contracts
  - name: bsc_defi
    database: bsc
    schema: defi
    tables:
      - name: ez_dex_swaps
  - name: thorchain
    database: flipside_prod_db
    schema: thorchain
    tables:
      - name: swaps
      - name: liquidity_actions
      - name: transfers
  - name: thorchain_core
    database: thorchain
    schema: core
    tables:
      - name: fact_transfers
  - name: flow_core
    database: flow
    schema: core
    tables:
      - name: ez_token_transfers
  - name: solana_core
    database: solana
    schema: core
    tables:
      - name: fact_transfers
      - name: dim_tokens
  - name: solana_defi
    database: solana
    schema: defi
    tables:
      - name: fact_swaps
  - name: near_core
    database: near
    schema: core
    tables:
      - name: fact_transfers
      - name: ez_dex_swaps
  - name: near_defi
    database: near
    schema: defi
    tables:
      - name: ez_dex_swaps
  - name: near_silver
    database: near
    schema: silver
    tables:
      - name: dex_swaps_s3
      - name: logs_s3
  - name: osmosis_silver
    database: osmosis
    schema: silver
    tables:
      - name: transactions
      - name: asset_metadata
      - name: prices_swaps
      - name: pool_token_prices_usd
      - name: swaps
  - name: osmosis_core
    database: osmosis
    schema: core
    tables:
      - name: fact_blocks
      - name: fact_transactions
      - name: fact_transfers
      - name: dim_tokens
  - name: osmosis_gov
    database: osmosis
    schema: gov
    tables:
      - name: fact_governance_votes
      - name: fact_validators
  - name: osmosis_defi
    database: osmosis
    schema: defi
    tables:
      - name: fact_swaps
  - name: axelar_core
    database: axelar
    schema: core
    tables:
      - name: fact_blocks
      - name: fact_transactions
      - name: fact_transfers
  - name: axelar_gov
    database: axelar
    schema: gov
    tables:
      - name: fact_governance_votes
      - name: fact_validators
  - name: cosmos_core
    database: cosmos
    schema: core
    tables:
      - name: fact_blocks
      - name: fact_transactions
      - name: fact_transfers
  - name: cosmos_gov
    database: cosmos
    schema: gov
    tables:
      - name: fact_governance_votes
      - name: fact_validators
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "CROSSCHAIN_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "CROSSCHAIN" }}
    tables:
      - name: asset_metadata_coin_market_cap_api
      - name: asset_metadata_coin_gecko_api
      - name: asset_ohlc_coin_market_cap_api
      - name: asset_historical_hourly_market_data_coin_gecko_api
      - name: asset_ohlc_coin_gecko_api
      - name: asset_prices_coin_gecko_api
  - name: bronze
    database: crosschain
    schema: bronze
    tables:
      - name: address_labels
      - name: data_science_uploads
      - name: legacy_prices
      - name: legacy_market_asset_metadata
      - name: legacy_hours
  - name: bronze_dev
    database: crosschain_dev
    schema: bronze
    tables:
      - name: address_labels
      - name: data_science_uploads
      - name: legacy_prices
      - name: legacy_market_asset_metadata
      - name: legacy_hours
  - name: ethereum_silver_dex
    database: ethereum
    schema: silver_dex
    tables:
      - name: complete_dex_swaps
      - name: complete_dex_liquidity_pools
  - name: optimism_silver_dex
    database: optimism
    schema: silver_dex
    tables:
      - name: complete_dex_swaps
      - name: complete_dex_liquidity_pools
  - name: avalanche_silver_dex
    database: avalanche
    schema: silver_dex
    tables:
      - name: complete_dex_swaps
      - name: complete_dex_liquidity_pools
  - name: polygon_silver_dex
    database: polygon
    schema: silver_dex
    tables:
      - name: complete_dex_swaps
      - name: complete_dex_liquidity_pools
  - name: bsc_silver_dex
    database: bsc
    schema: silver_dex
    tables:
      - name: complete_dex_swaps
      - name: complete_dex_liquidity_pools
  - name: arbitrum_silver_dex
    database: arbitrum
    schema: silver_dex
    tables:
      - name: complete_dex_swaps
      - name: complete_dex_liquidity_pools
  - name: solana_silver
    database: solana
    schema: silver
    tables:
      - name: token_metadata
      - name: solscan_tokens
      - name: events
  - name: avalanche_observ
    database: avalanche
    schema: silver_observability
    tables:
      - name: blocks_completeness
      - name: logs_completeness
      - name: receipts_completeness
      - name: traces_completeness
      - name: transactions_completeness
  - name: cosmos_observ
    database: cosmos
    schema: silver_observability
    tables:
      - name: blocks_completeness
      - name: transactions_completeness
  - name: osmosis_observ
    database: osmosis
    schema: silver_observability
    tables:
      - name: blocks_completeness
      - name: transactions_completeness
  - name: ethereum_observ
    database: ethereum
    schema: silver_observability
    tables:
      - name: blocks_completeness
      - name: logs_completeness
      - name: receipts_completeness
      - name: traces_completeness
      - name: transactions_completeness
  - name: polygon_observ
    database: polygon
    schema: silver_observability
    tables:
      - name: blocks_completeness
      - name: logs_completeness
      - name: receipts_completeness
      - name: traces_completeness
      - name: transactions_completeness
  - name: bsc_observ
    database: bsc
    schema: silver_observability
    tables:
      - name: blocks_completeness
      - name: logs_completeness
      - name: receipts_completeness
      - name: traces_completeness
      - name: transactions_completeness
  - name: arbitrum_observ
    database: arbitrum
    schema: silver_observability
    tables:
      - name: blocks_completeness
      - name: logs_completeness
      - name: receipts_completeness
      - name: traces_completeness
      - name: transactions_completeness
  - name: optimism_observ
    database: optimism
    schema: silver_observability
    tables:
      - name: blocks_completeness
      - name: logs_completeness
      - name: receipts_completeness
      - name: traces_completeness
      - name: transactions_completeness
  - name: base_observ
    database: base
    schema: silver_observability
    tables:
      - name: blocks_completeness
      - name: logs_completeness
      - name: receipts_completeness
      - name: traces_completeness
      - name: transactions_completeness
  - name: base_silver
    database: base
    schema: silver
    tables:
      - name: logs
      - name: decoded_logs
      - name: traces
      - name: transactions
      - name: abis
      - name: contracts
      - name: complete_event_abis
      - name: complete_nft_sales
  - name: base_silver_dex
    database: base
    schema: silver_dex
    tables:
      - name: complete_dex_swaps
      - name: complete_dex_liquidity_pools
  - name: base_core
    database: base
    schema: core
    tables:
      - name: fact_token_transfers
      - name: fact_traces
      - name: dim_contracts
  - name: base_defi
    database: base
    schema: defi
    tables: 
      - name: ez_dex_swaps
  - name: gnosis_silver
    database: gnosis
    schema: silver
    tables:
      - name: complete_event_abis
      - name: abis
      - name: contracts
      - name: traces
  - name: gnosis_silver_dex
    database: gnosis
    schema: silver_dex
    tables:
      - name: complete_dex_swaps
      - name: complete_dex_liquidity_pools
  - name: gnosis_core
    database: gnosis
    schema: core
    tables:
      - name: dim_contracts
  - name: gnosis_defi
    database: gnosis
    schema: defi
    tables:
      - name: ez_dex_swaps
  - name: gnosis_observ
    database: gnosis
    schema: silver_observability
    tables:
      - name: blocks_completeness
      - name: logs_completeness
      - name: receipts_completeness
      - name: traces_completeness
      - name: transactions_completeness
  - name: github
    schema: bronze_api
    tables:
      - name: github_repo_data
  - name: axelar_observ
    database: axelar
    schema: silver_observability
    tables:
      - name: blocks_completeness
      - name: transactions_completeness
  - name: terra_observ
    database: terra
    schema: silver_observability
    tables:
      - name: blocks_completeness
      - name: transactions_completeness
  - name: sei_observ
    database: sei
    schema: silver_observability
    tables:
      - name: blocks_completeness
      - name: transactions_completeness
  - name: aurora_observ
    database: aurora
    schema: silver_observability
    tables:
      - name: blocks_completeness
      - name: logs_completeness
      - name: receipts_completeness
      - name: transactions_completeness
  - name: bitcoin_observ
    database: bitcoin
    schema: silver_observability
    tables:
      - name: blocks_completeness
      - name: inputs_completeness
      - name: outputs_completeness
      - name: txs_completeness
  - name: flow_observ
    database: flow
    schema: silver_observability
    tables:
      - name: blocks_completeness
      - name: txs_completeness
  - name: near_observ
    database: near
    schema: silver_observability
    tables: 
      - name: blocks_completeness
      - name: chunks_completeness
      - name: logs_completeness
  - name: solana_observ
    database: solana
    schema: silver_observability
    tables: 
      - name: blocks_completeness
      - name: transactions_completeness
  - name: sei_core
    database: sei
    schema: core
    tables:
      - name: fact_msg_attributes
      - name: transactions_completeness
  - name: aptos_core
    database: aptos
    schema: core
    tables:
      - name: dim_tokens
  - name: aptos_observ
    database: aptos
    schema: silver_observability
    tables: 
      - name: blocks_completeness
      - name: transactions_completeness
