version: 2

sources:
  - name: legacy_db
    database: flipside_prod_db
    schema: silver
    tables:
      - name: prices_v2
      - name: market_asset_metadata
      - name: hours
  - name: legacy_silver_crosschain
    database: flipside_prod_db
    schema: silver_crosschain
    tables:
      - name: ntr
      - name: address_labels
  - name: legacy_dev_db
    database: flipside_dev_db
    schema: silver
    tables:
      - name: prices_v2
      - name: market_asset_metadata
      - name: hours
  - name: crosschain_dev_silver
    database: crosschain_dev
    schema: silver
    tables:
      - name: dates_table
  - name: ethereum_core
    database: ethereum
    schema: core
    tables:
      - name: fact_transactions
      - name: ez_nft_sales
      - name: ez_current_balances
      - name: ez_dex_swaps
  - name: ethereum_silver
    database: ethereum
    schema: silver
    tables:
      - name: logs
      - name: traces
      - name: transactions
      - name: labels
  - name: crosschain_silver
    database: crosschain
    schema: silver
    tables:
      - name: godmode_nft_minters
      - name: optimism_delegates
  - name: ethereum_silver_nft
    database: ethereum
    schema: silver_nft
    tables:
      - name: cryptopunk_sales
      - name: looksrare_sales
      - name: nftx_sales
      - name: opensea_sales
      - name: rarible_sales
      - name: seaport_sales
      - name: x2y2_sales
  - name: arbitrum_silver
    database: arbitrum
    schema: silver
    tables:
      - name: logs
      - name: traces
      - name: transactions
  - name: avalanche_silver
    database: avalanche
    schema: silver
    tables:
      - name: logs
      - name: traces
      - name: transactions
  - name: polygon_silver
    database: polygon
    schema: silver
    tables:
      - name: logs
      - name: traces
      - name: transactions
  - name: optimism_silver
    database: optimism
    schema: silver
    tables:
      - name: logs
      - name: traces
      - name: transactions
  - name: bsc_silver
    database: bsc
    schema: silver
    tables:
      - name: logs
      - name: traces
      - name: transactions
  - name: thorchain
    database: flipside_prod_db
    schema: thorchain
    tables:
      - name: swaps
      - name: liquidity_actions
  - name: bronze_streamline
    database: streamline
    schema: crosschain
    tables:
      - name: asset_metadata_coin_market_cap_api
      - name: asset_metadata_coin_gecko_api
      - name: asset_ohlc_coin_market_cap_api
      - name: asset_historical_hourly_market_data_coin_gecko_api
      - name: asset_ohlc_coin_gecko_api
  - name: bronze
    database: flipside_prod_db
    schema: bronze
    tables: 
      - name: prod_address_label_sink_291098491
  - name: Harmony_db
    database: HARMONY
    schema: PROD
    tables:
      - name: EZ_SUSHI_SWAPS
  - name: polygon
    database: POLYGON
    schema: SUSHI
    tables:
      - name: EZ_SWAPS
      - name: EZ_LENDING
      - name: EZ_BORROWING  
  - name: Arbitrum
    database: ARBITRUM
    schema: SUSHI
    tables:
      - name: EZ_SWAPS
      - name: EZ_LENDING
      - name: EZ_BORROWING 

  - name: Avalanche
    database: AVALANCHE
    schema: SUSHI
    tables:
      - name: EZ_SWAPS
      - name: EZ_LENDING
      - name: EZ_BORROWING  
  
  - name: BSC
    database: BSC
    schema: SUSHI
    tables:
      - name: EZ_SWAPS
      - name: EZ_LENDING
      - name: EZ_BORROWING  

  - name: Optimism
    database: OPTIMISM
    schema: SUSHI
    tables:
      - name: EZ_SWAPS

  - name: Gnosis  
    database: GNOSIS
    schema: SUSHI
    tables:
      - name: EZ_SWAPS
      - name: EZ_LENDING
      - name: EZ_BORROWING  
  - name: ethereum_db_sushi
    database: ethereum
    schema: sushi
    tables:
      - name: dim_distributor_reward_schedule
      - name: ez_lending
      - name: ez_borrowing