version: 2

sources:
  - name: legacy_db
    database: flipside_prod_db
    schema: silver
    tables:
      - name: prices_v2
      - name: market_asset_metadata
      - name: hours
  - name: legacy_silver_crosschain
    database: flipside_prod_db
    schema: silver_crosschain
    tables:
      - name: ntr
  - name: legacy_dev_db
    database: flipside_dev_db
    schema: silver
    tables:
      - name: prices_v2
      - name: market_asset_metadata
      - name: hours
  - name: crosschain_dev_silver
    database: crosschain_dev
    schema: silver
    tables:
      - name: dates_table
  - name: ethereum_core
    database: ethereum
    schema: core
    tables:
      - name: fact_transactions
      - name: ez_nft_sales
  - name: ethereum_silver
    database: ethereum
    schema: silver
    tables:
      - name: logs
      - name: traces
      - name: transactions
  - name: arbitrum_silver
    database: arbitrum
    schema: silver
    tables:
      - name: logs
      - name: traces
      - name: transactions
  - name: avalanche_silver
    database: avalanche
    schema: silver
    tables:
      - name: logs
      - name: traces
      - name: transactions
  - name: polygon_silver
    database: polygon
    schema: silver
    tables:
      - name: logs
      - name: traces
      - name: transactions
  - name: optimism_silver
    database: optimism
    schema: silver
    tables:
      - name: logs
      - name: traces
      - name: transactions
  - name: bsc_silver
    database: bsc
    schema: silver
    tables:
      - name: logs
      - name: traces
      - name: transactions
  - name: thorchain
    database: flipside_prod_db
    schema: thorchain
    tables:
      - name: swaps
      - name: liquidity_actions
  - name: crosschain_external
    schema: bronze
    loader: S3
    tables:
      - name: asset_metadata_api
        description: "all coins supported by provider"
        external:
          location: "@crosschain.bronze.analytics_external_tables/{{target.database}}/ASSET_METADATA_API"
          file_format: "( type = json, strip_outer_array = TRUE )"
          auto_refresh: true
          partitions:
            - name: provider
              data_type: string 
              expression: split_part(METADATA$FILENAME,'/',3)
        columns:
          - name: id
            data_type: string
            description: ""
          - name: symbol
            data_type: string
            description: ""
          - name: name
            data_type: string
            description: ""
      - name: asset_ohlc_coin_market_cap_api
        description: "all coins supported by provider"
        external:
          location: "@crosschain.bronze.analytics_external_tables/{{target.database}}/ASSET_OHLC_API/coinmarketcap"
          file_format: "( type = json, strip_outer_array = TRUE )"
          auto_refresh: true
          partitions:
            - name: _inserted_date
              data_type: string
              expression: substr((split_part(METADATA$FILENAME,'/',4)),16,10)
        columns:
          - name: id
            data_type: number
            description: ""
          - name: api_start_time
            data_type: number
          - name: api_end_time
            data_type: number
          - name: metadata
            data_type: string
            description: ""
          - name: data
            data_type: variant
            description: ""
  