version: 2

sources:
  - name: legacy_db
    database: flipside_prod_db
    schema: silver
    tables:
      - name: prices_v2
      - name: market_asset_metadata
      - name: hours
  - name: legacy_silver_crosschain
    database: flipside_prod_db
    schema: silver_crosschain
    tables:
      - name: ntr
      - name: address_labels
  - name: legacy_dev_db
    database: flipside_dev_db
    schema: silver
    tables:
      - name: prices_v2
      - name: market_asset_metadata
      - name: hours
  - name: crosschain_dev_silver
    database: crosschain_dev
    schema: silver
    tables:
      - name: dates_table
  - name: ethereum_core
    database: ethereum
    schema: core
    tables:
      - name: fact_transactions
      - name: ez_nft_sales
      - name: ez_current_balances
  - name: ethereum_silver
    database: ethereum
    schema: silver
    tables:
      - name: logs
      - name: traces
      - name: transactions
      - name: labels
  - name: crosschain_silver
    database: crosschain
    schema: silver
    tables:
      - name: godmode_nft_minters
      - name: optimism_delegates
  - name: ethereum_silver_nft
    database: ethereum
    schema: silver_nft
    tables:
      - name: cryptopunk_sales
      - name: looksrare_sales
      - name: nftx_sales
      - name: opensea_sales
      - name: rarible_sales
      - name: seaport_sales
      - name: x2y2_sales
  - name: arbitrum_silver
    database: arbitrum
    schema: silver
    tables:
      - name: logs
      - name: traces
      - name: transactions
  - name: avalanche_silver
    database: avalanche
    schema: silver
    tables:
      - name: logs
      - name: traces
      - name: transactions
  - name: polygon_silver
    database: polygon
    schema: silver
    tables:
      - name: logs
      - name: traces
      - name: transactions
  - name: optimism_silver
    database: optimism
    schema: silver
    tables:
      - name: logs
      - name: traces
      - name: transactions
  - name: bsc_silver
    database: bsc
    schema: silver
    tables:
      - name: logs
      - name: traces
      - name: transactions
  - name: thorchain
    database: flipside_prod_db
    schema: thorchain
    tables:
      - name: swaps
      - name: liquidity_actions
  - name: crosschain_external
    schema: bronze
    loader: S3
    tables:
      - name: asset_metadata_coin_market_cap_api
        description: "all coins supported by provider"
        external:
          location: "@crosschain.bronze.analytics_external_tables/{{target.database}}/ASSET_METADATA_API/coinmarketcap"
          file_format: "( type = json, strip_outer_array = TRUE )"
          auto_refresh: true
          partitions:
            - name: provider
              data_type: string 
              expression: split_part(METADATA$FILENAME,'/',3)
            - name: _inserted_date
              data_type: string
              expression: substr((split_part(METADATA$FILENAME,'/',4)),16,10)
        columns:
          - name: id
            data_type: string
            description: ""
          - name: symbol
            data_type: string
            description: ""
          - name: name
            data_type: string
            description: ""
      - name: asset_metadata_coin_gecko_api
        description: "all coins supported by provider"
        external:
          location: "@crosschain.bronze.analytics_external_tables/{{target.database}}/ASSET_METADATA_API/coingecko"
          file_format: "( type = json, strip_outer_array = TRUE )"
          auto_refresh: true
          partitions:
            - name: provider
              data_type: string 
              expression: split_part(METADATA$FILENAME,'/',3)
            - name: _inserted_date
              data_type: string
              expression: substr((split_part(METADATA$FILENAME,'/',4)),16,10)
        columns:
          - name: id
            data_type: string
            description: ""
          - name: symbol
            data_type: string
            description: ""
          - name: name
            data_type: string
            description: ""
      - name: asset_ohlc_coin_market_cap_api
        description: "all coins supported by provider"
        external:
          location: "@crosschain.bronze.analytics_external_tables/{{target.database}}/ASSET_OHLC_API/coinmarketcap"
          file_format: "( type = json, strip_outer_array = TRUE )"
          auto_refresh: true
          partitions:
            - name: _inserted_date
              data_type: string
              expression: substr((split_part(METADATA$FILENAME,'/',4)),16,10)
        columns:
          - name: id
            data_type: number
            description: ""
          - name: api_start_time
            data_type: number
          - name: api_end_time
            data_type: number
          - name: metadata
            data_type: string
            description: ""
          - name: data
            data_type: variant
            description: ""
      - name: asset_historical_hourly_market_data_coin_gecko_api
        description: "all coins supported by provider"
        external:
          location: "@crosschain.bronze.analytics_external_tables/{{target.database}}/ASSET_HISTORICAL_HOURLY_MARKET_DATA_API/coingecko"
          file_format: "( type = json, strip_outer_array = TRUE )"
          auto_refresh: true
          partitions:
            - name: _inserted_date
              data_type: string
              expression: substr((split_part(METADATA$FILENAME,'/',4)),16,10)
        columns:
          - name: id
            data_type: string
            description: ""
          - name: currency
            data_type: string
          - name: metadata
            data_type: variant
            description: ""
          - name: data
            data_type: variant
            description: ""
          - name: error
            data_type: string
            description: ""
      - name: asset_ohlc_coin_gecko_api
        description: "all coins supported by provider"
        external:
          location: "@crosschain.bronze.analytics_external_tables/{{target.database}}/ASSET_OHLC_API/coingecko"
          file_format: "( type = json, strip_outer_array = TRUE )"
          auto_refresh: true
          partitions:
            - name: _inserted_date
              data_type: string
              expression: substr((split_part(METADATA$FILENAME,'/',4)),16,10)
        columns:
          - name: id
            data_type: string
            description: ""
          - name: run_time
            data_type: timestamp_ntz
          - name: metadata
            data_type: string
            description: ""
          - name: data
            data_type: variant
            description: ""
          - name: error
            data_type: string
            description: ""
      
  